VOD.UI/Models/MembershipViewModels/CourseViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using VOD.UI.Models.DTOModels;

namespace VOD.UI.Models.MembershipViewModels
{
    public class CourseViewModel
    {
        public CourseDTO Course { get; set; }
        public InstructorDTO Instructor { get; set; }
        public IEnumerable<ModuleDTO> Modules { get; set; }
    }
}

VOD.UI/Models/MembershipViewModels/DashboardViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using VOD.UI.Models.DTOModels;

namespace VOD.UI.Models.MembershipViewModels
{
    public class DashboardViewModel
    {
        public List<List<CourseDTO>> Courses { get; set; }
    }
}

VOD.UI/Controllers/MembershipController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using VOD.Data.Data.Entities;
using VOD.UI.Models.DTOModels;
using VOD.UI.Models.MembershipViewModels;
using VOD.UI.Repositories;

namespace VOD.UI.Controllers
{
    public class MembershipController : Controller
    {
        private string _userId;
        private IReadRepository _repo;
        private readonly IMapper _mapper;
        public MembershipController(IHttpContextAccessor httpContextAccessor, UserManager<User> userManager, IMapper mapper, IReadRepository repo)
        {
            var user = httpContextAccessor.HttpContext.User;
            _userId = userManager.GetUserId(user);
            _mapper = mapper;
            _repo = repo;
        }

        [HttpGet]
        public IActionResult Dashboard()
        {
            var courseDtoObjects = _mapper.Map<List<CourseDTO>>(_repo.GetCourses(_userId));

            var dashboardModel = new DashboardViewModel();
            dashboardModel.Courses = new List<List<CourseDTO>>();

            var noOfRows = courseDtoObjects.Count <= 3 ? 1 :
                courseDtoObjects.Count / 3;
            for (var i = 0; i < noOfRows; i++)
            {
                dashboardModel.Courses.Add(courseDtoObjects.Take(3).ToList());
            }

            return View(dashboardModel);
        }

        [HttpGet]
        public IActionResult Course(int id)
        {
            var course = _repo.GetCourse(_userId, id);
            var mappedCourseDTOs = _mapper.Map<CourseDTO>(course);
            var mappedInstructorDTO = _mapper.Map<InstructorDTO>(course.Instructor);
            var mappedModuleDTOs = _mapper.Map<List<ModuleDTO>>(course.Modules);

            for (var i = 0; i < mappedModuleDTOs.Count; i++)
            {
                mappedModuleDTOs[i].Downloads =
                    course.Modules[i].Downloads.Count.Equals(0) ? null :
                    _mapper.Map<List<DownloadDTO>>(course.Modules[i].Downloads);

                mappedModuleDTOs[i].Videos =
                    course.Modules[i].Videos.Count.Equals(0) ? null :
                    _mapper.Map<List<VideoDTO>>(course.Modules[i].Videos);
            }

            var courseModel = new CourseViewModel
            {
                Course = mappedCourseDTOs,
                Instructor = mappedInstructorDTO,
                Modules = mappedModuleDTOs
            };

            return View(courseModel);
        }

        [HttpGet]
        public IActionResult Video(int id)
        {
            var video = _repo.GetVideo(_userId, id);
            var course = _repo.GetCourse(_userId, video.CourseId);
            var mappedVideoDTO = _mapper.Map<VideoDTO>(video);
            var mappedCourseDTO = _mapper.Map<CourseDTO>(course);
            var mappedInstructorDTO =
                _mapper.Map<InstructorDTO>(course.Instructor);

            // Create a LessonInfoDto object
            var videos = _repo.GetVideos(_userId, video.ModuleId).ToList();
            var count = videos.Count();
            var index = videos.IndexOf(video);
            var previous = videos.ElementAtOrDefault(index - 1);
            var previousId = previous == null ? 0 : previous.Id;
            var next = videos.ElementAtOrDefault(index + 1);
            var nextId = next == null ? 0 : next.Id;
            var nextTitle = next == null ? string.Empty : next.Title;
            var nextThumb = next == null ? string.Empty : next.Thumbnail;

            var videoModel = new VideoViewModel
            {
                Video = mappedVideoDTO,
                Instructor = mappedInstructorDTO,
                Course = mappedCourseDTO,
                LessonInfo = new LessonInfoDTO
                {
                    LessonNumber = index + 1,
                    NumberOfLessons = count,
                    NextVideoId = nextId,
                    PreviousVideoId = previousId,
                    CurrentVideoTitle = video.Title,
                    CurrentVideoThumbnail = video.Thumbnail,
                    NextVideoTitle = nextTitle,
                    NextVideoThumbnail = nextThumb
                }
            };

            return View(videoModel);
        }
    }
}

VOD.UI/Views/Membership/Course.cshtml
@model CourseViewModel

@{
    ViewData["Title"] = "Course";
}

<div class="membership top-margin course-content">
    <div class="row navigation-bar">
        <div class="col-sm-12">
            <a class="btn btn-primary" asp-controller="Membership" asp-action="Dashboard">
                <span class="glyphicon glyphicon-menu-left">Back to Dashboard</span>
            </a>
        </div>
    </div>    
</div>

VOD.UI/Views/Membership/Dashboard.cshtml
@model DashboardViewModel

@{
    ViewData["Title"] = "Dashboard";
}

<div class="membership top-margin">
    <h2 class="text-dark">Dashboard</h2>
    @foreach (var row in Model.Courses)
    {
        <div class="row">
            @foreach (var course in row)
            {
                @await Html.PartialAsync("_CoursePanelPartial", course);
            }
        </div>
    }
    <hr class="thick margin" />
</div>

VOD.UI/Views/Membership/_CoursePanelPartial.cshtml
@model CourseDTO

<div class="col-sm-4">
    <div class="panel course-listing">
        <img class="thumb" src="@Model.CourseImageUrl">
        <div class="panel-body">
            <h3 class="text-dark">@Model.CourseTitle</h3>
            <p>@Model.CourseDescription</p>
            <a class="btn btn-primary" href="~/Membership/Course/@Model.CourseId">View Course</a>
        </div>
    </div>
</div>